import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  // 15 sản phẩm Flash Sale đưa toàn bộ lên Store
  products: [
    {
      id: 401,
      name: "Ốp điện thoại",
      shopName: "Shincase",
      price: 20900,
      discount: "-16%",
      status: "ĐANG BÁN CHẠY",
      image:
        "https://down-vn.img.susercontent.com/file/vn-11134207-81ztc-mo7f7oce5zbaed_tn",
      progress: 85,
      sold: "1.2k",
      category: "Điện thoại",
      subCategory: "Phụ kiện",
      isFavorite: true,
      badge: "25.5",
    },
    {
      id: 402,
      name: "Ốp Lưng iPhone Trong Suốt Chống Ố Vàng Cao Cấp",
      shopName: "Phụ Kiện Số 1",
      price: 28500,
      discount: "-43%",
      status: "ĐANG BÁN CHẠY",
      image:
        "https://down-vn.img.susercontent.com/file/vn-11134207-81ztc-mk7vi7aqk3d46b_tn",
      progress: 90,
      sold: "2.4k",
      hasFreeShip: true,
      category: "Điện Thoại & Phụ Kiện",
      subCategory: "Ốp lưng",
      isFavorite: false,
      badge: "25.5",
    },
    {
      id: 403,
      name: "Bóng đèn LED",
      shopName: "LED Mall",
      price: 41900,
      discount: "-16%",
      status: "ĐANG BÁN CHẠY",
      image:
        "https://down-vn.img.susercontent.com/file/vn-11134207-81ztc-mlztdgl484coca_tn",
      progress: 60,
      sold: "850",
      category: "Gia dụng",
      subCategory: "Bóng đèn",
      isFavorite: true,
      badge: "25.5",
    },
    {
      id: 404,
      name: "Kính cường lực Full Màn Hình",
      shopName: "Shincase",
      price: 19000,
      discount: "-24%",
      status: "ĐANG BÁN CHẠY",
      image:
        "https://down-vn.img.susercontent.com/file/vn-11134207-81ztc-mkd7py8rc0eb57_tn",
      progress: 75,
      sold: "3.1k",
      category: "Điện thoại",
      subCategory: "Phụ kiện",
      isFavorite: false,
      badge: "25.5",
    },
    {
      id: 405,
      name: "Dây nhảy",
      shopName: "Sport Store",
      price: 21900,
      discount: "-39%",
      status: "ĐANG BÁN CHẠY",
      image:
        "https://down-vn.img.susercontent.com/file/vn-11134207-7ras8-mcud7vgdi5a7ce_tn",
      progress: 45,
      sold: "500",
      category: "Thể thao & Du lịch",
      subCategory: "Dây nhảy",
      isFavorite: true,
      badge: "25.5",
    },
    {
      id: 406,
      name: "Kính cường lực Full Màn Hình cho IP",
      shopName: "Shincase",
      price: 27855,
      discount: "-30%",
      status: "ĐANG BÁN CHẠY",
      image:
        "https://down-vn.img.susercontent.com/file/vn-11134207-7ra0g-m9zmtw4ti8ucfa_tn",
      progress: 95,
      sold: "9.2k",
      category: "Điện thoại",
      subCategory: "Phụ kiện",
      isFavorite: true,
      badge: "25.5",
    },
    {
      id: 407,
      name: "Dây Sạc Nhanh Type-C Bọc Dù Chống Đứt",
      shopName: "Phụ Kiện Số 1",
      price: 32000,
      discount: "-20%",
      status: "ĐANG BÁN CHẠY",
      image: "https://picsum.photos/300/300?random=407",
      progress: 50,
      sold: "1.1k",
      category: "Điện Thoại & Phụ Kiện",
      subCategory: "Cáp sạc",
      isFavorite: false,
      badge: "25.5",
    },
    {
      id: 408,
      name: "Khăn Lau Đa Năng Sợi Microfiber Siêu Thấm Hút",
      shopName: "Home Decor Official",
      price: 15500,
      discount: "-15%",
      status: "ĐANG BÁN CHẠY",
      image: "https://picsum.photos/300/300?random=408",
      progress: 40,
      sold: "4.5k",
      category: "Nhà Cửa & Đời Sống",
      subCategory: "Khăn lau",
      isFavorite: false,
      badge: "25.5",
    },
    {
      id: 409,
      name: "Kính Cường Lực Full Màn Hình Độ Cứng 9H",
      shopName: "Phụ Kiện Số 1",
      price: 49000,
      discount: "-50%",
      status: "ĐANG BÁN CHẠY",
      image: "https://picsum.photos/300/300?random=409",
      progress: 88,
      sold: "12k+",
      category: "Điện Thoại & Phụ Kiện",
      subCategory: "Kính cường lực",
      isFavorite: true,
      badge: "25.5",
    },
    {
      id: 410,
      name: "Giá Đỡ Điện Thoại Để Bàn Gấp Gọn Tiện Lợi",
      shopName: "Audio Global",
      price: 60000,
      discount: "-12%",
      status: "ĐANG BÁN CHẠY",
      image: "https://picsum.photos/300/300?random=410",
      progress: 30,
      sold: "200",
      category: "Điện Thoại & Phụ Kiện",
      subCategory: "Giá đỡ điện thoại",
      isFavorite: false,
      badge: "25.5",
    },
    {
      id: 411,
      name: "Lót Chuột Gaming Khổ Lớn Bo Viền Chắc Chắn",
      shopName: "Audio Global",
      price: 22500,
      discount: "-25%",
      status: "ĐANG BÁN CHẠY",
      image: "https://picsum.photos/300/300?random=411",
      progress: 65,
      sold: "3.3k",
      category: "Máy Tính & Laptop",
      subCategory: "Lót chuột",
      isFavorite: true,
      badge: "25.5",
    },
    {
      id: 412,
      name: "Móc Khóa Hoạt Hình Dễ Thương Nhiều Mẫu",
      shopName: "Gia Dụng Mall",
      price: 18900,
      discount: "-35%",
      status: "ĐANG BÁN CHẠY",
      image: "https://picsum.photos/300/300?random=412",
      progress: 70,
      sold: "6k",
      category: "Phụ kiện Trang Sức",
      subCategory: "Móc khóa",
      isFavorite: false,
      badge: "25.5",
    },
    {
      id: 413,
      name: "Ví Nam Mini Cầm Tay Da PU Cao Cấp",
      shopName: "Fashion Men",
      price: 35000,
      discount: "-18%",
      status: "ĐANG BÁN CHẠY",
      image: "https://picsum.photos/300/300?random=413",
      progress: 55,
      sold: "150",
      category: "Thời Trang Nam",
      subCategory: "Ví da",
      isFavorite: true,
      badge: "25.5",
    },
    {
      id: 414,
      name: "Thắt Lưng Nam Da Bò Khóa Tự Động Thời Trang",
      shopName: "Fashion Men",
      price: 42000,
      discount: "-40%",
      status: "ĐANG BÁN CHẠY",
      image: "https://picsum.photos/300/300?random=414",
      progress: 80,
      sold: "7k",
      category: "Thời Trang Nam",
      subCategory: "Thắt lưng",
      isFavorite: false,
      badge: "25.5",
    },
    {
      id: 415,
      name: "Túi Đeo Chéo Nữ Mini Phong Cách Hàn Quốc",
      shopName: "Beauty Store",
      price: 29900,
      discount: "-22%",
      status: "ĐANG BÁN CHẠY",
      image: "https://picsum.photos/300/300?random=415",
      progress: 92,
      sold: "1.9k",
      category: "Túi Ví Nữ",
      subCategory: "Túi đeo chéo",
      isFavorite: true,
      badge: "25.5",
    },
  ],
  // Thời gian đếm ngược
  totalSeconds: 2 * 3600 + 15 * 60,
  loading: false,
  error: null,
};

const flashSaleSlice = createSlice({
  name: "flashSale",
  initialState,
  reducers: {
    setFlashSaleProducts: (state, action) => {
      state.products = action.payload;
    },
    tick: (state) => {
      if (state.totalSeconds > 0) {
        state.totalSeconds -= 1;
      }
    },
  },
});
export const { tick } = flashSaleSlice.actions;
export default flashSaleSlice.reducer;

// Selector tính toán quy đổi từ tổng số giây ra Giờ, Phút, Giây chuẩn chỉnh
export const selectFlashSaleTimer = (state) => {
  const total = state.flashSale.totalSeconds;

  const hours = Math.floor(total / 3600);
  const minutes = Math.floor((total % 3600) / 60);
  const seconds = total % 60;

  // Trả về chuỗi có 2 chữ số (ví dụ: 09, 05, 12)
  return {
    hours: String(hours).padStart(2, "0"),
    minutes: String(minutes).padStart(2, "0"),
    seconds: String(seconds).padStart(2, "0"),
  };
};
